server:
  port: 9050

spring:
  application:
    name: graph-database-service
  kafka:
    bootstrap-servers: kafka:9092
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      healthcheck:
        enabled: true
  instance:
    prefer-ip-address: true
